### ISSUE TITLE
Investigate "permalink" in classic editor Navis slideshow

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-mstoday#83]

**Comment by benlk** [comment]
https://github.com/INN/largo/blob/v0.6.4/lib/navis-slideshows/navis-slideshows.php#L188

```css
.navis-slideshow .slide-permalink { display: none; }
```
